- src/app/image/[name]/scan/[scanId]/page.tsx
- src/app/library/[name]/page.tsx
- src/app/library/page.tsx
- src/components/vulnerability-url-menu.tsx
- Fixes incorrect routing of GHSA vulnerabilities to NVD instead of GitHub Advisories
- Adds context menu for vulnerabilities with multiple reference URLs
- Implements intelligent URL detection based on vulnerability ID patterns
As reported in #21, when viewing vulnerability details for GitHub Security Advisories (GHSA), the "View" button was incorrectly routing to `nvd.nist.gov` instead of the appropriate GitHub advisory page. This happened because the code was simply using the first URL from the references array without considering the vulnerability type.
Created a new `VulnerabilityUrlMenu` component that:
1. **Single URL**: Shows a simple link button when only one reference is available
2. **Multiple URLs**: Displays a dropdown menu with all available options
3. **Smart Detection**: …
> Fix vulnerability URL routing with context menu for multiple links

- scripts/init-database.js
Fixes a critical bug preventing PostgreSQL connections from working properly.
The `init-database.js` script contained a duplicate `fs` constant declaration on line 78 within the `testPostgreSQLConnection` function. Since `fs` was already imported at the module level (line 3), this redeclaration caused:
```
ReferenceError: Cannot access 'fs' before initialization
```
PR #26 successfully implemented PostgreSQL support with sound connection logic. However, during subsequent refactoring to improve the connection test mechanism, a duplicate `const fs = require('fs')` was inadvertently added inside the `testPostgreSQLConnection` function. 
This scoping issue prevented the PostgreSQL connection test from executing, causing all PostgreSQL connections to fail and fall back to SQLite.
Removed the …
> Fix PostgreSQL connection failure due to duplicate fs declaration

- scripts/init-database-with-fallback.js
- scripts/start.sh
Fixes authentication failures when using bundled PostgreSQL database due to credential mismatches between initialization scripts.
The application was failing to start with the following error:
```
Error: P1000: Authentication failed against database server, the provided database credentials for `harborguard` are not valid.
```
This occurred when:
1. Container starts and creates bundled PostgreSQL with random password
2. Container restarts and PostgreSQL data persists
3. New container generates different random password
4. Authentication fails due to password mismatch
- `start.sh` was generating a random password on each container start using `openssl rand`
- `init-database-with-fallback.js` was using hardcoded credentials (`harborguard:harborguard`)
- When PostgreSQL data persisted …
> Fix database authentication mismatch for bundled PostgreSQL

- package-lock.json
- package.json
- src/app/api/scans/aggregated/route.ts
- src/app/api/scans/route.ts
- src/app/api/vulnerabilities/route.ts
- src/app/image/[name]/page.tsx
- src/app/image/[name]/scan/[scanId]/page.tsx
- src/app/library/[name]/page.tsx
- src/app/library/page.tsx
- src/components/ui/scroll-area.tsx
- src/components/vulnerability-details-modal.tsx
- Added a new VulnerabilityDetailsModal component that displays comprehensive vulnerability information
- Integrated modal into vulnerability library and scan results pages
- Fixed vulnerability aggregation to properly combine results from both Trivy and Grype scanners
- **Vulnerability Details Modal**: Created a comprehensive modal component that displays:
- CVE ID, severity, and CVSS scores
- Detailed vulnerability descriptions
- Package information with installed and fixed versions
- Risk assessment metrics (CVSS vector, exploit availability, EPSS score)
- Timeline showing published and last modified dates
- List of affected images with navigation links
- False positive tracking
- Clickable hyperlinks for all references and external resources
- **Vulnerability Library Page** (): 
- …
> feat: Add comprehensive vulnerability details modal

- src/app/library/page.tsx
- Added clickable navigation to affected images badges in vulnerability library
- Added clickable navigation to false positive badges in vulnerability library
- Both badge types now navigate to `/image/[imageName]` pages for detailed image information
- Updated `/app/harborguard/src/app/library/page.tsx` to add click handlers to badges
- Image names are parsed to remove tags before navigation (splits on `:` and takes first part)
- Added `stopPropagation()` to prevent row click interference
- Added hover effects (`hover:opacity-80`) for better user experience
> feat: Add clickable navigation for library badges

- prisma/migrations/20250906032053_add_protocol_field_to_repository/migration.sql
- prisma/schema.prisma
- src/app/api/repositories/[id]/images/[imageName]/tags/route.ts
- src/app/api/repositories/[id]/images/route.ts
- src/app/api/repositories/[id]/test/route.ts
- src/app/api/repositories/route.ts
- src/app/api/repositories/test/route.ts
- src/app/image/[name]/page.tsx
- src/app/library/[name]/page.tsx
- src/app/repositories/page.tsx
- src/components/add-repository-dialog.tsx
- src/components/data-table.tsx
- src/components/historical-scans-table.tsx
- src/components/new-scan-modal.tsx
- src/contexts/AppContext.tsx
- src/generated/openapi.json
- src/hooks/useScans.ts
- src/lib/scanner/DatabaseAdapter.ts
- src/lib/scanner/ScanExecutor.ts
- Adds support for displaying multiple registry badges when the same image exists in different registries
- Implements 'Scan All Images' button for private repositories to scan all images with their actual tags
- Fixes data handling to preserve registry information throughout the application
- Updated data table to aggregate and display all registries for images with the same name
- Registry column now shows multiple badges (Docker Hub, Local Docker, custom registries)
- Pre-computes registry information during data grouping for better performance
- Added 'Scan All Images' button next to 'Load Images' for private repositories
- Automatically fetches actual tags from registry instead of defaulting to 'latest'
- Provides progress tracking with success/failure counts
- Adds 500ms delay …
> feat: Add multi-registry badges and scan all functionality

- src/components/docker-image-selector.tsx
- Resolves React warning about duplicate keys in Docker image selector component
- Uses composite key to ensure uniqueness across all Docker images
The Docker image selector was using truncated image IDs (12 characters) as React keys. When multiple images shared the same ID prefix, React would throw a warning about duplicate keys.
Changed the key from a simple `image.id` to a composite key: `${image.repository}-${image.tag}-${image.id}-${index}`
This ensures each item has a unique key even when image IDs collide.
> Fix duplicate key warning in Docker image selector

- src/app/api/repositories/[id]/test/route.ts
- src/app/api/repositories/test/route.ts
- Adds POST /api/repositories/test endpoint for testing new repository configurations before saving
- Adds POST /api/repositories/[id]/test endpoint for testing existing repository connections
- Supports DockerHub, GHCR, and generic registry connection testing with authentication validation
> Add missing repository test endpoints

- prisma/migrations/20250916210221_fix_integer_overflow_image_size/migration.sql
- prisma/schema.prisma
- src/app/api/images/[id]/route.ts
- src/app/api/scans/local-bulk/route.ts
- src/app/api/scans/upload/route.ts
- src/app/image/[name]/page.tsx
- src/app/image/[name]/scan/[scanId]/page.tsx
- src/lib/scanner/DatabaseAdapter.ts
- src/lib/type-utils.ts
Fixes #90 - Integer overflow error when scanning Docker images larger than ~2.14GB
The `Image.sizeBytes` field was using PostgreSQL's INT4 (32-bit signed integer) which can only store values up to 2,147,483,647. Docker images larger than this size (approximately 2.14GB) would cause an integer overflow error during scanning.
Changed the `sizeBytes` field from `Int?` to `BigInt?` throughout the codebase to support values up to 9,223,372,036,854,775,807 bytes (~9.2 exabytes).
- **Schema**: Changed `Image.sizeBytes` from `Int?` to `BigInt?` in Prisma schema
- **Database**: Generated and applied migration to alter column type to BIGINT
- **Backend**: Updated DatabaseAdapter to use `BigInt()` for size conversions
- **API**: Fixed serialization to convert BigInt to strings for JSON responses
- …
> Fix integer overflow when storing large Docker image sizes

- src/app/api/audit-logs/route.ts
- src/lib/audit-logger.ts
- src/middleware.ts
- Adds IP address protection when `NEXT_PUBLIC_DEMO_MODE=true`
- Replaces all real IP addresses with "DEMO_PROTECT" in audit logs
- Ensures user privacy in public demo environments
- Modified `getUserIpFromRequest()` in `src/lib/audit-logger.ts` to return "DEMO_PROTECT" in demo mode
- Updated `getUserIp()` in `src/middleware.ts` to mask IPs when demo mode is enabled  
- Added IP protection in `src/app/api/audit-logs/route.ts` for API-created logs
- Also protects IPs in `scanComplete()` and `systemError()` audit logger methods
> feat: Protect user IPs in demo mode

- src/components/new-scan-modal.tsx
**Summary**
Fix the name of the docker image in the scan modal window.
**Solution**
Replaced use of fullName instead of image name.
**Test Plan**
Try scanning a private repository again and verify that images with names such as “x86_64/imageName” and “aarch64/imageName” are displayed correctly.
> Fix: docker image in scan modal window

- src/app/api/patches/[id]/status/route.ts
- Fixed "Do not know how to serialize a BigInt" error when fetching patch operation status
- Used existing `serializeForJson` utility function to handle BigInt conversion consistently
The `/api/patches/[id]/status` endpoint was failing because the `Image` model contains a `sizeBytes` field of type `BigInt`, which cannot be directly serialized to JSON.
Updated the endpoint to use the existing `serializeForJson` utility function that properly handles BigInt conversion throughout the codebase, ensuring consistency with other API endpoints.
> Fix BigInt serialization error in patch status API

- src/app/api/scans/[id]/scanner-results/route.ts
- src/generated/openapi.json
This PR fixes a catastrophic performance issue where the `/api/scans` endpoint was returning 251.6MB of data for just 38 scans, making the application unusable.
| Metric | Before | After | Improvement |
|--------|--------|-------|-------------|
| **Response Size** | 251.6 MB | 5-40 KB | **99.998% reduction** |
| **Response Time** | 9-10 seconds | 45-52ms | **99.5% faster** |
| **TTFB** | 9.2-10.2s | 45ms | **99.5% faster** |
| **Bandwidth per request** | 251.6 MB | 0.04 MB | **6,290x less** |
The `/api/scans` endpoint was including complete scanner outputs in every response:
- `syftResults`: 107KB per scan (SBOM data)
- `grypeResults`: 90KB per scan (vulnerability scanner output)  
- `diveResults`: 67KB per scan (layer analysis)
- `trivyResults`: 43KB per scan (vulnerability scanner …
> Critical Fix: Reduce API payload by 99.998% (251MB → 5KB)

- package-lock.json
- package.json
- src/app/api/image/[name]/scan/[scanId]/xlsx-report/route.ts
- src/app/images/[name]/[scanId]/page.tsx
- src/generated/openapi.json
- src/lib/xlsx-report.ts
- Added comprehensive XLSX export functionality for security scan reports
- Implemented dropdown menu for selecting between PDF and XLSX export formats
- Created professionally styled multi-sheet Excel reports with HarborGuard branding
- **Summary Sheet**: Professional overview with logo, scan details, and vulnerability statistics
- **Scanner-Specific Sheets**: Dedicated tabs for Trivy, Grype, Dockle, Syft SBOM, and OSV results
- **Combined Vulnerabilities Sheet**: Aggregated view of all vulnerabilities sorted by severity
- HarborGuard branding with anchor logo (⚓)
- Color-coded severity levels (Critical: Red, High: Orange, Medium: Amber, Low: Blue, Info: Gray)
- Formatted headers with background colors
- Optimized column widths and row heights
- Clean, organized data presentation
- …
> feat: Add XLSX export with multi-sheet reports

- .gitignore
- .puppeteerrc.cjs
- Dockerfile
- src/app/api/image/[name]/scan/[scanId]/pdf-report/route.ts
- Fixes PDF generation in Docker environment by adding Chromium and Puppeteer configuration
- Resolves issue #125
PDF generation was failing in Docker because Puppeteer couldn't find Chromium browser, resulting in errors when trying to generate PDF reports.
- Added `chromium` package and required dependencies to Alpine Docker image
- Added font packages for proper text rendering (`ttf-freefont`, `freetype`, `harfbuzz`)
- Total size increase is minimal (~100MB) compared to full Chrome installation
- Set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` to prevent downloading Chromium during npm install
- Set `PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser` to use system Chromium
- Added `.puppeteerrc.cjs` for proper Puppeteer configuration
- Updated launch arguments for better stability in …
> fix: Add Puppeteer support in Docker for PDF generation

- src/app/images/page.tsx
- src/app/page.tsx
- src/components/section-cards.tsx
- src/components/table/unified-table.tsx
- src/components/vulnerability-scatterplot.tsx
- Added multi-select capability to the images table with checkboxes
- Implemented bulk delete functionality for selected images
- Fixed checkbox interaction to prevent navigation when selecting
- Enable row selection in UnifiedTable with proper click handling
- Add selection state management and bulk delete confirmation
- Show selection count and delete button when items are selected
- Delete selected images in parallel with progress feedback
> Add multi-select and bulk delete for images

- src/lib/registry/providers/base/EnhancedRegistryProvider.ts
- src/lib/registry/providers/generic/GenericOCIProvider.ts
- src/lib/registry/providers/gitlab/GitLabRegistryHandler.ts
- src/lib/registry/providers/nexus/NexusProvider.ts
Fixes the "unknown flag: --creds" error when copying images between registries using skopeo.
- Updated `copyImage` method to use `--src-creds` and `--dest-creds` instead of `--creds`
- Added `shouldVerifyTLSForRegistry` helper method for source registry TLS verification
- Added proper credential quoting in GenericOCIProvider and NexusProvider
- Removed TLS flag from GitLab getSkopeoAuthArgs (now handled separately by caller)
- Added optional sourceCredentials parameter to copyImage method
- Split TLS verification into separate `--src-tls-verify` and `--dest-tls-verify` flags
The skopeo copy command requires different flags than skopeo inspect:
- skopeo inspect uses: `--creds "user:pass"`
- skopeo copy uses: `--src-creds "user:pass"` and `--dest-creds "user:pass"`
This fix maintains …
> Fix skopeo copy credentials flags

- prisma/migrations/20251004191157_add_vulnerability_indexes/migration.sql
- src/app/api/vulnerabilities/route.ts
- src/app/library/page.tsx
Implements database-level optimizations and true backend pagination for the vulnerabilities API to improve query performance and scalability.
- Composite index on `(cveId, severity DESC, cvssScore DESC)` - Optimizes GROUP BY and ORDER BY operations
- Composite index on `(cveId, scanId)` - Speeds up COUNT DISTINCT aggregation
- Covering index on `(severity, cveId, cvssScore DESC, packageName)` - Supports filtered queries
- GIN trigram indexes on `cveId`, `packageName`, `description`, `title` - Enables fast ILIKE text searches
- Enabled `pg_trgm` extension for trigram matching
- Changed from ROW_NUMBER() window functions to direct GROUP BY aggregation
- Replaced self-join with DISTINCT ON for finding top severity per CVE
- Added explicit type casting for PostgreSQL Severity enum to text
- …
> Optimize vulnerabilities API with PostgreSQL indexes and backend pagination

- src/app/api/repositories/route.ts
- src/components/add-repository-dialog.tsx
- src/lib/registry/RegistryService.ts
Adds support for configuring a custom Docker registry port for Nexus repositories, enabling HarborGuard to work with Nexus instances that expose their Docker registry on non-standard ports.
Nexus Repository Manager typically uses:
- Port 8081 for the main Nexus API
- Port 5000 (default) for Docker registry operations
However, many deployments use custom ports for the Docker registry (e.g., port 5443 for HTTPS). Previously, HarborGuard always defaulted to port 5000 for Docker operations, making it incompatible with custom port configurations.
Added an optional `registryPort` field that allows users to specify the port used for Docker push/pull operations, separate from the main Nexus API port.
- **`src/lib/registry/RegistryService.ts`**: Added `registryPort` parameter to …
> feat: add Docker registry port configuration for Nexus repositories

- src/lib/registry/providers/nexus/NexusProvider.ts
Implements fallback logic in NexusProvider for Skopeo operations (inspect, pull, push) to handle different Nexus Docker registry configurations.
- Override `inspectImage()`, `pullImage()`, and `pushImage()` methods in NexusProvider
- Implement two-tier fallback pattern:
1. First attempt: `{host}:{dockerPort}/{image}:{tag}`
2. Fallback attempt: `{host}:{dockerPort}/{repositoryName}/{image}:{tag}`
When Skopeo operations fail on the first attempt, the provider automatically retries using the repository name prefix. This handles Nexus configurations where some require the repository name in the image path while others don't.
For this to work properly, Nexus must have:
- A configured HTTP/HTTPS Docker connector (not just path-based routing on the API port)
- The `registryPort` field set to the …
> Add repository name fallback for Nexus Skopeo operations
